"""Generate typed WRAM accessors from the pinned disassembly's RAM map (names/addresses only).

Output: native/generated/ram_map.hpp defining `thor::WramNames`, a mixin whose members have the
same names as the disassembly (`SamusXPosition()`, `Enemy_XPosition(k)`, `Boyon_speed(k)` ...).
Struct fields become `Struct_field`.  Every accessor takes an optional byte offset (the 65816
X/Y index register) that is added to the address, so `LDA $0F7A,x` is `Enemy_XPosition(x)`.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "reference/sm-disassembly/src/memory.asm"
OUTPUT = ROOT / "native/generated/ram_map.hpp"
PAL = 0


def number(text):
    text = text.strip()
    if text.startswith("$"):
        return int(text[1:], 16)
    return int(text)


def condition(text):
    text = text.strip()
    match = re.fullmatch(r"!PAL\s*(==|!=)\s*(\$?\w+)", text)
    if match:
        value = number(match[2])
        return (PAL == value) if match[1] == "==" else (PAL != value)
    if text == "!PAL":
        return bool(PAL)
    raise ValueError("Unhandled conditional: " + text)


def parse():
    entries = []          # (name, address, size)
    names = {}
    address = 0
    struct_base = None
    struct_name = None
    stack = []            # (active_before, taken)
    active = True
    for raw in SOURCE.read_text().splitlines():
        line = raw.split(";")[0].strip()
        if not line:
            continue
        head = line.split()[0]
        if head == "if":
            stack.append((active, condition(line[2:])))
            active = active and stack[-1][1]
            continue
        if head == "else":
            outer, taken = stack[-1]
            active = outer and not taken
            continue
        if head == "endif":
            active, _ = stack.pop()
            continue
        if not active:
            continue
        if head == "org":
            address = number(line.split()[1])
            continue
        if head == "struct":
            parts = line.split()
            struct_name, struct_base = parts[1], number(parts[2])
            address = struct_base
            continue
        if head == "endstruct":
            struct_name = struct_base = None
            continue
        if head in ("check", "warnpc", "print", "assert", "incsrc"):
            continue
        match = re.fullmatch(r"(\.?[A-Za-z_]\w*):\s*(?:skip\s+(\S+))?", line)
        if match:
            label, size_text = match[1], match[2]
            size = number(size_text) if size_text else 0
            if label.startswith("."):
                if struct_name is None:
                    continue
                label = struct_name + "_" + label[1:]
            elif label in ("Stoke",):
                pass
            entries.append((label, address & 0xFFFFFF, size))
            address += size
            continue
        match = re.fullmatch(r"skip\s+(\S+)", line)
        if match:
            address += number(match[1])
            continue
    return entries


def symbol_addresses():
    """Authoritative addresses from the assembled symbol file (asar resolves struct skips)."""
    table = {}
    path = ROOT / "build/reference.sym"
    if not path.exists():
        return table
    for line in path.read_text().splitlines():
        match = re.fullmatch(r"([0-9A-F]{2}):([0-9A-F]{4}) ([A-Za-z_][\w.]*)", line)
        if match:
            table[match[3]] = (int(match[1], 16) << 16) | int(match[2], 16)
    return table


def main():
    entries = parse()
    symbols = symbol_addresses()
    fixed = []
    for name, address, size in entries:
        dotted = name.replace("_", ".", 1) if "_" in name else name
        for candidate in (dotted, name):
            if candidate in symbols:
                address = symbols[candidate]
                break
        fixed.append((name, address, size))
    entries = fixed
    lines = ["// Generated by tools/gen_ram_map.py from the pinned disassembly memory map.",
             "// Names and addresses only; no cartridge data.",
             "#pragma once", '#include "thor/wram.hpp"', "namespace thor {",
             "struct WramNames : Wram {"]
    seen = set()
    count = 0
    for name, address, size in entries:
        wram = address & 0xFFFFFF
        if wram >= 0x7E0000 or wram < 0x2000:
            pass
        if wram >= 0x7E0000:
            offset = wram - 0x7E0000
        elif wram < 0x2000:
            offset = wram
        else:
            continue   # hardware registers / ROM addresses
        if offset >= 0x20000 or name in seen or not re.fullmatch(r"[A-Za-z_]\w*", name):
            continue
        seen.add(name)
        count += 1
        if size == 1:
            lines.append(f"    Byte {name}(uint32_t x = 0) {{ return byte_at(0x{offset:05X} + x); }}")
        elif size == 2:
            lines.append(f"    Word {name}(uint32_t x = 0) {{ return word_at(0x{offset:05X} + x); }}")
        elif size == 3:
            lines.append(f"    Long {name}(uint32_t x = 0) {{ return long_at(0x{offset:05X} + x); }}")
        else:
            # Arrays: word access by default (indexed by the 65816 byte offset); raw bytes via Name_bytes().
            lines.append(f"    Word {name}(uint32_t x = 0) {{ return word_at(0x{offset:05X} + x); }}")
            lines.append(f"    uint8_t* {name}_bytes(uint32_t x = 0) {{ return bytes_at(0x{offset:05X} + x); }}")
        lines.append(f"    static constexpr uint32_t {name}_address = 0x{offset:05X};")
    lines += ["};", "}", ""]
    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Generated {count} WRAM names")


if __name__ == "__main__":
    sys.exit(main())
