"""Generate address metadata, never ROM bytes, from the pinned Asar symbols."""
import argparse
import re
from pathlib import Path

COMMIT = "11c906f547edc1b57f5a5923cf977fe7b50a3694"


CPP_KEYWORDS = {"alignas", "and", "asm", "auto", "bool", "break", "case", "catch", "char", "class", "const",
    "continue", "default", "delete", "do", "double", "else", "enum", "explicit", "export", "extern", "false",
    "float", "for", "friend", "goto", "if", "inline", "int", "long", "namespace", "new", "not", "operator",
    "or", "private", "protected", "public", "register", "return", "short", "signed", "sizeof", "static",
    "struct", "switch", "template", "this", "throw", "true", "try", "typedef", "union", "unsigned", "using",
    "virtual", "void", "volatile", "while", "xor"}


def write_all_labels(symbol_file: Path, output: Path):
    """Every named address in the gameplay/data banks $80-$B4, for native translation work.

    Address metadata only (0BSD disassembly labels); no cartridge bytes."""
    seen = {}
    for line in symbol_file.read_text().splitlines():
        match = re.fullmatch(r"([0-9A-F]{2}):([0-9A-F]{4}) ([A-Za-z_]\w*)", line)
        if match and 0x80 <= int(match[1], 16) <= 0xB4 and match[3] not in CPP_KEYWORDS:
            seen.setdefault(match[3], int(match[1] + match[2], 16))
    lines = ["// Generated by tools/reference_index.py. Address metadata only.",
             "#pragma once", "#include <cstdint>", "namespace thor::labels {"]
    lines += [f"inline constexpr uint32_t {name} = 0x{value:06X};" for name, value in sorted(seen.items())]
    lines += ["}", ""]
    output.write_text("\n".join(lines), encoding="utf-8")


def generate(symbol_file: Path, output: Path):
    labels = {}
    for line in symbol_file.read_text().splitlines():
        match = re.fullmatch(r"([0-9A-F]{2}):([0-9A-F]{4}) ([A-Za-z_][\w]*)", line)
        if match:
            labels[match[3]] = int(match[1] + match[2], 16)
    rooms = []
    source = Path(__file__).resolve().parents[1] / "reference/sm-disassembly/src/bank_8F.asm"
    source_text = source.read_text()
    door_counts = {}
    for match in re.finditer(r"^(RoomDoors_\w+):([^:]*)", source_text, re.MULTILINE):
        # Count only the contiguous word entries, never infer a terminator from
        # subsequent scroll/PLM bytes: vanilla door lists have no sentinel.
        entries = []
        for line in match[2].splitlines():
            line = line.split(";")[0].strip()
            if not line:
                continue
            if not re.fullmatch(r"dw Door_\w+", line):
                break
            entries.append(line)
        door_counts[match[1]] = len(entries)
    state_names = re.findall(r"^(RoomState_\w+):", source.read_text(), re.MULTILINE)
    for name in re.findall(r"^(RoomHeader_\w+):", source.read_text(), re.MULTILINE):
        address = labels[name]
        short = name[len("RoomHeader_"):]
        states = [(labels[key], key) for key in state_names
                  if key == f"RoomState_{short}" or
                  re.fullmatch(re.escape(f"RoomState_{short}_") + r"\d+", key)]
        if states:
            header_text = source_text.split(name + ":", 1)[1].split("RoomState_", 1)[0]
            door_list = re.search(r"%doorList\((\w+)\)", header_text)
            if not door_list or door_list[1] not in door_counts:
                raise ValueError(f"Missing bounded door list for {name}")
            rooms.append((address, min(states)[0], short, door_counts[door_list[1]]))
    rooms.sort()
    if len(rooms) < 200 or labels.get("RoomHeader_LandingSite") != 0x8F91F8:
        raise ValueError("Symbols are not the expected anchored NTSC reference")
    required = [
        "Tileset_Pointers", "CRE_Tiles_Compressed", "CRE_TileTable_Compressed",
        "SamusSpritemapTable", "SamusSpritemapTableIndices_TopHalf",
        "SamusSpritemapTableIndices_BottomHalf",
        "SamusTopHalfTilesAnimation_TilesDefinitionPointers",
        "SamusBottomHalfTilesAnimation_TilesDefinitionPointers",
        "SamusTilesAnimation_AnimationDefinitionPointers", "SamusPalettes_PowerSuit",
        "SamusPhysicsConstants_YSubAccelerationInAir", "SamusPhysicsConstants_YAccelerationInAir",
        "SamusPhysicsConstants_InitialYSpeeds_Jumping", "SamusPhysicsConstants_InitialYSubSpeeds_Jumping",
        "SamusXSpeedTable_Normal",
        "SlopeDefinitions_SlopeTopXOffsetByYPixel", "SquareSlopeDefinitions_Bank94",
        "Use_StatePointer_inX", "UNUSED_RoomStateCheck_Door_8FE5EB",
        "RoomStateCheck_MainAreaBossIsDead", "RoomStateCheck_EventHasBeenSet",
        "RoomStateCheck_BossIsDead", "UNUSED_RoomStateCheck_Morphball_8FE640",
        "RoomStateCheck_MorphballAndMissiles", "RoomStateCheck_PowerBombs",
        "UNUSED_RoomStateCheck_SpeedBooster_8FE678",
        "BeamSpeeds_Horizontal_Vertical", "BeamSpeeds_Diagonal",
        "ProjectileCooldowns_Uncharged", "BeamAutoFireCooldowns",
        "ProjectileOriginOffsetsByDirection_ProjectileX_Default",
        "ProjectileOriginOffsetsByDirection_ProjectileY_Default",
        "ProjectileOriginOffsetsByDirection_ProjX_Moonwalk_Running",
        "ProjectileOriginOffsetsByDirection_ProjY_Moonwalk_Running", "PoseDefinitions_YOffset",
        "ProjectileDataTable_Uncharged_Power", "Tiles_PowerBeam", "BeamPalettes_Power",
        "InstList_PLM_BlueDoorFacingLeftOpened_40", "InstList_PLM_BlueDoorFacingLeftOpened_41",
        "InstList_PLM_BlueDoorFacingUpOpened_42", "InstList_PLM_BlueDoorFacingUpOpened_43",
        "LoadStationListPointers", "PoseDefinitions", "AnimationDelayTable", "MapRoomPointers",
        "SRAMMapData_size", "SRAMMapData_offset",
        "TransitionTable", "PLMEntries_saveStation", "EnemyHeaders_Elevator",
        "EnemyHeaders_ShipTop", "EnemyHeaders_ShipBottomEntrance", "InstList_ShipTop", "InstList_ShipBottom", "InstList_ShipEntrancePad_Closed",
        "SamusPhysicsConstants_InitialYSpeeds_BombJump", "SamusPhysicsConstants_InitialYSubSpeeds_BombJump",
        "SamusPhysicsConstants_XAccelerations_DashHeld", "SamusPhysicsConstants_XSubAccelerations_DashHeld",
        "SamusPhysicsConstants_MaxXExtraRunSpeeds_NoSpeedBooster", "SamusPhysicsConstants_MaxXExtraRunSubSpeeds_NoSpeedBooster",
        "DrawInst_DoorFacingLeft_A677", "DrawInst_DoorFacingRight_A683",
        "DrawInst_DoorFacingUp_A68F", "DrawInst_DoorFacingDown_A69B",
        "DrawInst_DoorFacingLeft_A9B3", "DrawInst_DoorFacingRight_A9EF",
        "DrawInst_DoorFacingUp_AA2B", "DrawInst_DoorFacingDown_AA67",
        "InstList_PLM_BlueDoorFacingLeftClosed", "InstList_PLM_BlueDoorFacingRightClosed",
        "InstList_PLM_BlueDoorFacingUpClosed_42", "InstList_PLM_BlueDoorFacingUpClosed_43",
        "PLMEntries_rightwardsExtension", "PLMEntries_leftwardsExtension", "PLMEntries_upwardsExtension", "PLMEntries_downwardsExtension", "PLMEntries_ScrollPLM",
        "DrawInst_GreyDoorFacingLeft_0", "DrawInst_YellowDoorFacingLeft_0", "DrawInst_GreenDoorFacingLeft_0", "DrawInst_RedDoorFacingLeft_0",
        "DrawInst_ItemChozoOrb", "DrawInst_ItemOrb_0", "ItemPLMGFX_Bombs", "ItemPLMGFX_MorphBall",
        "ProjectileDataTable_NonBeam_Missile", "ProjectileCooldowns_NonBeamProjectiles", "MissileAccelerations",
        "ProjectileAccelerations_X", "ProjectileAccelerations_Y", "BombTimerResetValue", "Tiles_Standard_Sprite_0", "Tiles_Standard_Sprite_1",
    ]
    # Additional native enemy/animation callbacks. These are source addresses,
    # never embedded cartridge data or a machine-code execution table.
    prefixes = ("Instruction_Torizo_", "InstList_Torizo_", "Function_Torizo_", "TorizoInitial_",
                "Palette_Torizo_", "Instruction_CommonAA_", "Instruction_CommonB2_",
                "Instruction_PirateWalking_", "InstList_PirateWalking_", "Function_PirateWalking_",
                "InstList_PirateWall_", "Instruction_PirateWall_", "Inst_PirateWall_", "Function_PirateWall_",
                "InstList_EnemyProjectile_Torizo", "InstList_EnemyProjectile_Pirate_MotherBrain_Laser",
                "InstList_EnemyProjectile_BombTorizoExplosionSwipe")
    names = set(required)
    for bank in ("AA", "B2", "86"):
        for name in re.findall(r"^(\w+):", (source.parent / ("bank_" + bank + ".asm")).read_text(), re.MULTILINE):
            if name.startswith(prefixes) and name in labels:
                names.add(name)
    required = sorted(names | {"EnemyHeaders_BombTorizo", "EnemyHeaders_PirateGreyWalking", "EnemyHeaders_PirateGreyWall",
        "Tiles_Torizo", "TorizoInitial_XPosition", "TorizoInitial_YPosition", "TorizoInitial_XRadius", "TorizoInitial_YRadius",
        "Instruction_Torizo_StandingUpMovement_IndexInY_XVelocities", "Instruction_Torizo_StandingUpMovement_IndexInY_YVelocities",
        "Instruction_Torizo_BombTorizoWalkingMovement_Normal_IndexInY_velocities",
        "Instruction_Torizo_BTWalkingMovement_Faceless_IndexInY_velocities", "RTL_AAC2C8",
        "ExtendedSpritemap_Torizo_Blank", "InstList_Elevator", "ProjectileDataTable_NonBeam_Bomb", "Initial_Palette_spritePalette0",
        "PLMEntries_BombTorizosCrumblingChozo", "InstList_PLM_1x1RespawningShotBlock", "InstList_PLM_1x1ShotBlock", "InstList_PLM_1x1RespawningCrumbleBlock", "InstList_PLM_BombTorizosCrumblingChozo",
        "DrawInst_BombTorizosCrumblingChozo_0", "DrawInst_BombTorizosCrumblingChozo_1",
        "Instruction_PLM_PreInstruction_inY", "Instruction_PLM_Sleep", "Instruction_PLM_Delete",
        "Instruction_PLM_TransferBytesToVRAM", "Instruction_PLM_SpawnBombTorizoStatueBreakingWithArgY",
        "Instruction_PLM_QueueSong1MusicTrack", "InitAI_EnemyProjectile_BombTorizoExplosiveSwipe_Xpositions",
        "InitAI_EnemyProjectile_BombTorizoExplosiveSwipe_Yposition"})
    lines = ["// Generated by tools/reference_index.py. Address metadata only.",
             "// Source: InsaneFirebat/sm_disassembly (0BSD), pinned " + COMMIT,
             "#pragma once", "#include <cstdint>", "namespace thor::reference {",
             'inline constexpr char commit[] = "' + COMMIT + '";',
             "struct RoomRef { uint32_t header, state; const char* name; uint8_t door_count; };",
             "inline constexpr RoomRef rooms[] = {"]
    lines += [f'    {{0x{a:06X}, 0x{s:06X}, "{n}", {d}}},' for a, s, n, d in rooms]
    lines += ["};"]
    for name in required:
        lines.append(f"inline constexpr uint32_t {name} = 0x{labels[name]:06X};")
    lines += ["struct DoorScroll { uint16_t script; uint8_t screen, color; };", "inline constexpr DoorScroll door_scrolls[] = {"]
    # Extract the small native scroll callbacks used by early room links.
    for match in re.finditer(r"^(DoorASM_\w+):([\s\S]*?)(?=^\w+:|\Z)", source_text, re.MULTILINE):
        body = match[2]
        if re.search(r"^\s+(?:B[A-Z]{2}|JMP|JSR|JSL)\b", body, re.MULTILINE):
            continue
        value = None
        for line in body.splitlines():
            immediate = re.search(r"LDA\.B #\$([0-9A-F]{2})", line)
            if immediate: value = int(immediate[1], 16)
            target = re.search(r"STA\.L Scrolls(?:\+(\d+))?\s", line)
            if target and value is not None:
                lines.append(f"    {{0x{labels[match[1]] & 0xFFFF:04X}, {int(target[1] or 0)}, {value}}},")
    lines += ["};"]
    lines += ["}", ""]
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines), encoding="utf-8")
    write_all_labels(symbol_file, output.parent / "reference_labels.hpp")
    print(f"Indexed {len(rooms)} rooms from {len(labels)} named symbols")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("symbols", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    generate(args.symbols, args.output)
