"""Generate address metadata, never ROM bytes, from the pinned Asar symbols."""
import argparse
import re
from pathlib import Path

COMMIT = "11c906f547edc1b57f5a5923cf977fe7b50a3694"


def generate(symbol_file: Path, output: Path):
    labels = {}
    for line in symbol_file.read_text().splitlines():
        match = re.fullmatch(r"([0-9A-F]{2}):([0-9A-F]{4}) ([A-Za-z_][\w]*)", line)
        if match:
            labels[match[3]] = int(match[1] + match[2], 16)
    rooms = []
    source = Path(__file__).resolve().parents[1] / "reference/sm-disassembly/src/bank_8F.asm"
    source_text = source.read_text()
    door_counts = {}
    for match in re.finditer(r"^(RoomDoors_\w+):([^:]*)", source_text, re.MULTILINE):
        # Count only the contiguous word entries, never infer a terminator from
        # subsequent scroll/PLM bytes: vanilla door lists have no sentinel.
        entries = []
        for line in match[2].splitlines():
            line = line.split(";")[0].strip()
            if not line:
                continue
            if not re.fullmatch(r"dw Door_\w+", line):
                break
            entries.append(line)
        door_counts[match[1]] = len(entries)
    state_names = re.findall(r"^(RoomState_\w+):", source.read_text(), re.MULTILINE)
    for name in re.findall(r"^(RoomHeader_\w+):", source.read_text(), re.MULTILINE):
        address = labels[name]
        short = name[len("RoomHeader_"):]
        states = [(labels[key], key) for key in state_names
                  if key == f"RoomState_{short}" or
                  re.fullmatch(re.escape(f"RoomState_{short}_") + r"\d+", key)]
        if states:
            header_text = source_text.split(name + ":", 1)[1].split("RoomState_", 1)[0]
            door_list = re.search(r"%doorList\((\w+)\)", header_text)
            if not door_list or door_list[1] not in door_counts:
                raise ValueError(f"Missing bounded door list for {name}")
            rooms.append((address, min(states)[0], short, door_counts[door_list[1]]))
    rooms.sort()
    if len(rooms) < 200 or labels.get("RoomHeader_LandingSite") != 0x8F91F8:
        raise ValueError("Symbols are not the expected anchored NTSC reference")
    required = [
        "Tileset_Pointers", "CRE_Tiles_Compressed", "CRE_TileTable_Compressed",
        "SamusSpritemapTable", "SamusSpritemapTableIndices_TopHalf",
        "SamusSpritemapTableIndices_BottomHalf",
        "SamusTopHalfTilesAnimation_TilesDefinitionPointers",
        "SamusBottomHalfTilesAnimation_TilesDefinitionPointers",
        "SamusTilesAnimation_AnimationDefinitionPointers", "SamusPalettes_PowerSuit",
        "SamusPhysicsConstants_YSubAccelerationInAir", "SamusPhysicsConstants_YAccelerationInAir",
        "SamusPhysicsConstants_InitialYSpeeds_Jumping", "SamusPhysicsConstants_InitialYSubSpeeds_Jumping",
        "SamusXSpeedTable_Normal",
        "SlopeDefinitions_SlopeTopXOffsetByYPixel", "SquareSlopeDefinitions_Bank94",
        "Use_StatePointer_inX", "UNUSED_RoomStateCheck_Door_8FE5EB",
        "RoomStateCheck_MainAreaBossIsDead", "RoomStateCheck_EventHasBeenSet",
        "RoomStateCheck_BossIsDead", "UNUSED_RoomStateCheck_Morphball_8FE640",
        "RoomStateCheck_MorphballAndMissiles", "RoomStateCheck_PowerBombs",
        "UNUSED_RoomStateCheck_SpeedBooster_8FE678",
    ]
    lines = ["// Generated by tools/reference_index.py. Address metadata only.",
             "// Source: InsaneFirebat/sm_disassembly (0BSD), pinned " + COMMIT,
             "#pragma once", "#include <cstdint>", "namespace thor::reference {",
             'inline constexpr char commit[] = "' + COMMIT + '";',
             "struct RoomRef { uint32_t header, state; const char* name; uint8_t door_count; };",
             "inline constexpr RoomRef rooms[] = {"]
    lines += [f'    {{0x{a:06X}, 0x{s:06X}, "{n}", {d}}},' for a, s, n, d in rooms]
    lines += ["};"]
    for name in required:
        lines.append(f"inline constexpr uint32_t {name} = 0x{labels[name]:06X};")
    lines += ["}", ""]
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines))
    print(f"Indexed {len(rooms)} rooms from {len(labels)} named symbols")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("symbols", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    generate(args.symbols, args.output)
